[build-system]
requires = ["setuptools==75.8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "openapi-to-rust-bindings"
version = "0.2.2"
description = "Load openapi-to-rust binding metadata into rust-sdk-generator Bindings"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT OR Apache-2.0"}
dependencies = [
  "rust-sdk-generator @ git+https://github.com/adriendellagaspera/rust-sdk-generator.git@fdd9901f24095761e8daf6a83ee2e5de63da8ddf",
  "tree-sitter==0.25.2",
  "tree-sitter-rust==0.24.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["openapi_to_rust_bindings"]
