"""Explicit Rust runtime contract used by deterministic SDK emission."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RustFacadeRuntime:
    """Consumer-owned support paths referenced by generated SDK code."""

    error_type: str = "SdkError"
    error_module: str = "error"
    error_exports: tuple[str, ...] = (
        "ApiError",
        "SdkError",
        "TransportError",
        "TransportErrorKind",
    )
    sse_module: str = "crate::streaming"
    sse_function: str = "json_events"
    generated_marker: str = (
        "// @generated by rust-sdk-compiler; do not edit by hand.\n"
    )


DEFAULT_RUNTIME = RustFacadeRuntime()
